CREATE SCHEMA SistBiblioteca;
USE SistBiblioteca;

CREATE TABLE USUARIOS(
	ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    PERFIL ENUM ("bibliotecario", "leitor") NOT NULL
);

CREATE TABLE LIVROS(
	ID_LIV INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    AUTOR VARCHAR(50) NOT NULL,
    ANO_PUBLICADO INT,
    QTD_DISPONIVEL INT NOT NULL
);

CREATE TABLE EMPRESTIMOS(
	ID_EMPRES INT AUTO_INCREMENT PRIMARY KEY,
    LIVRO_ID INT,
    LEITOR_ID INT,
    DATA_EMPRES DATE NOT NULL,
    DEVOLUCAO_PRESISTA DATE NOT NULL,
    DEVOLUCAO_REAL DATE NOT NULL,
    ESTATUS ENUM ("ativo", "devolvido", "atrasado") NOT NULL 
);